 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"AfterStep Terminal", "aterm", "/usr/share/pixmaps/aterm.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Gxmessage", "gxmessage", "/usr/share/icons/hicolor/48x48/apps/gxmessage.png" },
     {"KAlarm", "kalarm -caption KAlarm ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Rockbox Utility", "RockboxUtility", "/usr/share/pixmaps/rbutil.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"gootool", "gootool "},
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"GNU Octave", "xterm -e /usr/bin/octave", "///usr/share/octave/3.8.1/imagelib/octave-logo.svg" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Sage", "xterm -e /opt/sage/sage -notebook", "/usr/share/pixmaps/sage-notebook.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"0 A.D.", "0ad", "/usr/share/pixmaps/0ad.png" },
     {"Antichamber", "\"/home/ross/Antichamber/Antichamber.sh\"", "///home/ross/Antichamber/AntichamberIcon.png" },
     {"Aquaria", "\"/home/ross/humblebundle/aquaria/aquaria\""},
     {"Avadon: The Black Fortress", "\"/home/ross/humblebundle/avadon/Avadon\"", "///home/ross/humblebundle/avadon/Avadon.png" },
     {"BZFlag", "bzflag", "///usr/share/bzflag/bzflag-48x48.png" },
     {"Battle Worlds: Kronos", "/usr/games/battleworldskronos ", "/usr/local/share/icons/hicolor/16x16/apps/battleworldskronos.png" },
     {"Battle for Wesnoth", "wesnoth", "/usr/share/pixmaps/wesnoth-icon.png" },
     {"Battle for Wesnoth (devel)", "wesnoth-devel", "/usr/share/icons/wesnoth-devel-icon.xpm" },
     {"Battle for Wesnoth Map Editor", "wesnoth -e", "/usr/share/pixmaps/wesnoth_editor-icon.png" },
     {"Beat Hazard Ultra", "\"/home/ross/humblebundle/beathazard/bin/BeatHazard\"", "///home/ross/humblebundle/beathazard/SmileLogo.png" },
     {"Braid", "\"/home/ross/braid/braid\""},
     {"Chocolate Doom", "chocolate-doom", "/usr/share/icons/chocolate-doom.png" },
     {"Commander Zod", "/usr/bin/commander-zod", "///usr/lib/commander-zod/assets/icon.png" },
     {"Cortex Command", "\"/home/ross/humblebundle/CortexCommand/CortexCommand\"", "///home/ross/humblebundle/CortexCommand/CortexCommand.png" },
     {"Descent 1 Rebirth ", "d1x-rebirth", "/usr/share/pixmaps/d1x-rebirth.xpm" },
     {"Desura", "/opt/desura/desura ", "///opt/desura/data/desura.png" },
     {"Desura", "desura", "/usr/share/icons/hicolor/256x256/apps/desura.png" },
     {"Desura (Force Update)", "xterm -e /opt/desura/desura -f", "///opt/desura/data/desura.png" },
     {"Doomseeker", "doomseeker", "///usr/share/doomseeker/icon.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Dune Legacy", "dunelegacy", "/usr/share/pixmaps/dunelegacy.png" },
     {"Dungeon Defenders", "\"/home/ross/humblebundle/dungeondefenders/DungeonDefenders\""},
     {"Dwarf Fortress", "dwarffortress", "///usr/share/pixmaps/dwarffortress.png" },
     {"EDuke32", "eduke32", "/usr/share/pixmaps/eduke32.png" },
     {"Fabled Lands App", "flands", "///usr/share/pixmaps/flands/icon.jpg" },
     {"Freeorion", "freeorion", "/usr/share/pixmaps/freeorion.png" },
     {"GZDoom", "gzdoom ", "/usr/share/pixmaps/gzdoom.png" },
     {"Gargoyle", "gargoyle", "/usr/share/pixmaps/gargoyle.png" },
     {"Gens/GS", "gens", "///usr/share/gens/gensgs_48x48.png" },
     {"Globulation 2", "glob2", "/usr/share/icons/hicolor/48x48/apps/glob2-icon-48x48.png" },
     {"Golly", "golly", "/usr/share/pixmaps/golly.xpm" },
     {"Hedgewars", "hedgewars ", "/usr/share/pixmaps/hedgewars.png" },
     {"Hexen 2", "hexen2", "/usr/share/pixmaps/hexen2.png" },
     {"Jamestown", "\"/home/ross/humblebundle/jamestown/Jamestown\"", "///home/ross/humblebundle/jamestown/jamestown.png" },
     {"Kega Fusion", "kega-fusion", "/usr/share/pixmaps/kega-fusion.png" },
     {"Liberal Crime Squad", "xterm -e crimesquad"},
     {"Lugaru", "\"/home/ross/humblebundle/lugaru/lugaru\""},
     {"M.A.X. Reloaded", "maxr", "/usr/share/pixmaps/maxr.png" },
     {"Marathon (Aleph One)", "alephone-marathon"},
     {"Marathon 2: Durandal (Aleph One)", "alephone-marathon2"},
     {"Marathon Infinity (Aleph One)", "alephone-infinity"},
     {"MegaGlest", "megaglest", "/usr/share/pixmaps/megaglest.png" },
     {"MegaGlest Map Editor", "megaglest_editor", "/usr/share/pixmaps/megaglest.png" },
     {"MegaGlest Model Viewer", "megaglest_g3dviewer", "/usr/share/pixmaps/megaglest.png" },
     {"Minecraft", "minecraft", "///usr/share/pixmaps/minecraft.png" },
     {"Oblige", "Oblige", "/usr/share/pixmaps/oblige.png" },
     {"Odalaunch", "odalaunch", "/usr/share/pixmaps/odalaunch.png" },
     {"Odamex", "odamex -waddir /usr/share/doom", "/usr/share/pixmaps/odamex.png" },
     {"Oolite", "oolite", "/usr/share/pixmaps/oolite-icon.png" },
     {"OpenArena", "/usr/bin/openarena", "/usr/share/pixmaps/openarena.png" },
     {"OpenRA", "openra", "/usr/share/icons/hicolor/16x16/apps/openra.png" },
     {"OpenRA Map Editor", "openra-editor", "/usr/share/icons/hicolor/32x32/apps/openra-editor.png" },
     {"OpenTTD", "openttd", "/usr/share/icons/hicolor/16x16/apps/openttd.png" },
     {"OpenXcom", "openxcom", "/usr/share/icons/hicolor/48x48/apps/openxcom.png" },
     {"Pioneer", "/usr/bin/pioneer", "/usr/share/pixmaps/pioneer.png" },
     {"Pioneers", "pioneers", "/usr/share/icons/hicolor/48x48/apps/pioneers.png" },
     {"Pioneers Editor", "pioneers-editor", "/usr/share/icons/hicolor/48x48/apps/pioneers-editor.png" },
     {"Pioneers Server", "pioneers-server-gtk", "/usr/share/icons/hicolor/48x48/apps/pioneers-server.png" },
     {"PlayOnLinux", "playonlinux", "/usr/share/pixmaps/playonlinux32.png" },
     {"PrBoom Plus", "prboom-plus", "/usr/share/pixmaps/prboom-plus.png" },
     {"Progress Quest", "/usr/bin/progressquest", "///usr/share/pixmaps/progressquest.png" },
     {"Project 64", "/usr/bin/project64", "///usr/share/pixmaps/project64.png" },
     {"QMC2 (SDLMAME)", "qmc2-sdlmame", "///usr/share/qmc2/img/mame.png" },
     {"Quake III Arena", "/usr/bin/quake3", "///usr/share/pixmaps/quake3.png" },
     {"Race for the Galaxy", "rftg", "///usr/share/rftg/rftg.svg" },
     {"RetroArch-Phoenix", "retroarch-phoenix", "///usr/share/pixmaps/retroarch-phoenix.png" },
     {"Return to the Roots", "s25rttr", "/usr/share/pixmaps/s25rttr.xpm" },
     {"Scorched3d", "scorched3d", "/usr/share/icons/hicolor/48x48/apps/scorched3d.png" },
     {"ScummVM", "scummvm", "/usr/share/pixmaps/scummvm.xpm" },
     {"Seven Kingdoms: Ancient Adversaries", "/usr/bin/7kaa", "/usr/share/pixmaps/7kaa.ico" },
     {"Shank", "\"/home/ross/humblebundle/shank/bin/Shank\""},
     {"Simutrans", "simutrans", "/usr/share/pixmaps/simutrans.png" },
     {"Space Pirates and Zombies", "\"/home/ross/humblebundle/spaz/SPAZ\"", "///home/ross/humblebundle/spaz/SPAZ.png" },
     {"SpringLobby", "springlobby"},
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Super Hexagon", "\"/home/ross/humblebundle/superhexagon/SuperHexagon\""},
     {"Super Mario War", "smw", "/usr/share/pixmaps/smw.png" },
     {"Super Meat Boy", "\"/home/ross/supermeatboy/SuperMeatBoy\""},
     {"Technic Launcher", "technic-launcher", "///usr/share/pixmaps/technic-launcher.png" },
     {"Teeworlds", "teeworlds", "/usr/share/pixmaps/teeworlds.png" },
     {"The Ur-Quan Masters", "uqm", "/usr/share/pixmaps/uqm.png" },
     {"ToME4", "/usr/bin/tome4", "/usr/share/pixmaps/tome4.png" },
     {"UFO2000", "ufo2000", "/usr/share/pixmaps/ufo2000.png" },
     {"UrW", "urw", "/usr/share/pixmaps/urwicon-48.png" },
     {"VCMI", "vcmiclient", "/usr/share/icons/hicolor/32x32/apps/vcmiclient.png" },
     {"Wah!Cade", "wahcade", "/usr/share/pixmaps/wahcade.png" },
     {"Wargus - Warcraft II", "/usr/local/bin/wargus"},
     {"Warzone 2100", "warzone2100", "/usr/share/icons/warzone2100.png" },
     {"Widelands", "widelands", "/usr/share/pixmaps/widelands.png" },
     {"Xboard", "xboard", "/usr/share/icons/hicolor/48x48/apps/xboard.png" },
     {"Xonotic (GLX)", "/usr/bin/xonotic-glx", "///usr/share/pixmaps/xonotic.png" },
     {"Xonotic (SDL)", "/usr/bin/xonotic-sdl", "///usr/share/pixmaps/xonotic.png" },
     {"ZDoom", "zdoom ", "/usr/share/pixmaps/zdoom.png" },
     {"Zsnes", "zsnes", "/usr/share/pixmaps/zsnes.png" },
     {"ccGo", "/usr/bin/ccgo", "///usr/share/pixmaps/ccgo/ccgo.png" },
     {"eBoard", "eboard", "/usr/share/pixmaps/eboard.png" },
     {"ezQuake", "/usr/bin/ezquake", "///usr/share/pixmaps/ezquake.ico" },
     {"gShogi", "gshogi", "/usr/share/pixmaps/gshogi.png" },
     {"gootool", "gootool "},
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"ACBF Viewer", "acbfv ", "/usr/share/icons/hicolor/16x16/apps/acbfv.png" },
     {"DjView4", "djview4 ", "/usr/share/icons/hicolor/32x32/apps/djvulibre-djview4.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"E-book Viewer", "ebook-viewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"Feh", "feh ", "///usr/share/feh/images/feh.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/pixmaps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"MComix", "mcomix ", "/usr/share/icons/hicolor/16x16/apps/mcomix.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Deluge", "deluge-gtk ", "/usr/share/icons/hicolor/16x16/apps/deluge.png" },
     {"DogeCoin", "/usr/bin/dogecoin-qt", "///usr/share/pixmaps/dogecoin.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"Earlybird", "thunderbird-earlybird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird-earlybird.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Gnaural", "gnaural ", "///usr/share/gnaural/pixmaps/gnaural-icon.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Musetup-gtk", "musetup-gtk", "/usr/share/pixmaps/museek_alt2.png" },
     {"Odamex server", "xterm -e odasrv", "/usr/share/pixmaps/odasrv.png" },
     {"OpenArena Server", "xterm -e /usr/bin/openarena-server", "/usr/share/pixmaps/openarena-server.png" },
     {"PS3 Media Server", "ps3mediaserver", "/usr/share/pixmaps/pms.png" },
     {"PrBoom Plus Server", "xterm -e prboom-plus-game-server", "/usr/share/pixmaps/prboom-plus-game-server.png" },
     {"QTScrobbler", "qtscrob", "/usr/share/icons/hicolor/16x16/apps/qtscrob.png" },
     {"Skype", "env PULSE_LATENCY_MSEC=60 skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamSpeak 3", "teamspeak3", "/usr/share/pixmaps/teamspeak3.xpm" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Vidalia", "vidalia", "/usr/share/icons/hicolor/16x16/apps/vidalia.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/icons/hicolor/16x16/apps/wicd-gtk.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calibre", "calibre ", "/usr/share/pixmaps/calibre-gui.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Edit E-book", "ebook-edit ", "/usr/share/pixmaps/calibre-ebook-edit.png" },
     {"Evolution", "evolution ", "/usr/share/icons/hicolor/16x16/apps/evolution.png" },
     {"Foxit Reader", "foxitreader ", "/usr/share/pixmaps/foxitreader.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Sigil", "sigil", "/usr/share/icons/hicolor/16x16/apps/sigil.png" },
     {"Xpdf", "xpdf ", "/usr/share/pixmaps/xpdf.xpm" },
     {"Zathura", "zathura "},
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Java Mission Control", "jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Java Monitoring and Management Console", "jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Java VisualVM", "jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"KDevelop 4", "kdevelop ", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDevelop 4 (Pick Session)", "kdevelop --ps", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"Netbeans", "netbeans", "/usr/share/pixmaps/netbeans.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Ario", "ario", "/usr/share/icons/hicolor/16x16/apps/ario.png" },
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"AutoZen", "autozen"},
     {"AutoZen (colorbox)", "autozen -colorbox"},
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"Ex Falso", "exfalso", "/usr/share/icons/hicolor/64x64/apps/exfalso.png" },
     {"Gnaural", "gnaural ", "///usr/share/gnaural/pixmaps/gnaural-icon.png" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"Mixxx", "pasuspender mixxx", "/usr/share/pixmaps/mixxx-icon.png" },
     {"MusicBrainz Picard", "picard ", "/usr/share/icons/hicolor/16x16/apps/picard.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Quod Libet", "quodlibet", "/usr/share/icons/hicolor/64x64/apps/quodlibet.png" },
     {"Rdio", "rdio", "/usr/share/icons/hicolor/16x16/apps/rdio.svg" },
     {"Rubyripper", "rrip_gui", "/usr/share/icons/hicolor/128x128/apps/rubyripper.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"SMPlayer YouTube Browser", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png" },
     {"Sonata", "sonata", "/usr/share/pixmaps/sonata.png" },
     {"Spotify", "spotify ", "/usr/local/share/icons/hicolor/16x16/apps/spotify-client.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"tuxguitar", "tuxguitar  -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false", "///usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Dolphin", "dolphin -caption Dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Dolphin", "dolphin  -caption Dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Razercfg", "qrazercfg", "/usr/share/pixmaps/razer.svg" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Vifm", "xterm -e vifm ", "/usr/share/pixmaps/vifm.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

