call shortcut#map('<Space> T n', 'Test -> Nearest', 'TestNearest')
call shortcut#map('<Space> T f', 'Test -> File', 'TestFile')
call shortcut#map('<Space> T F', 'Test -> Suite', 'TestSuite')
call shortcut#map('<Space> T .', 'Test -> Last', 'TestLast')
call shortcut#map('<Space> T v', 'Test -> Visit', 'TestVisit')
